language: node_js
node_js:
 - node
before_script: 
 - npm install
script:
 - npm run coverage
branches:
  only:
  - master 
  - /^greenkeeper/.*$/
notifications:
email:
  on_failure: change
  on_success: change