export const Constants = {
    SCOPE_ATTRIBUTE_NAME     : '$scope',
    EVENT_ATTRIBUTE_NAME     : '$event',
    REPEAT_ATTRIBUTE_NAME    : 'cp-repeat',
    REPEAT_INDEX_NAME        : '$index',
    REPEAT_ATTRIBUTE_OPERATOR: 'in',
    MODEL_ATTRIBUTE_NAME     : 'cp-model',
    CLICK_ATTRIBUTE_NAME     : 'cp-click',
    SHOW_ATTRIBUTE_NAME      : 'cp-show',
    IF_ATTRIBUTE_NAME        : 'cp-if',
    STEP_ATTRIBUTE_NAME      : 'cp-step',
    MAX_ATTRIBUTE_NAME       : 'cp-max',
    MAX_LENGTH_ATTRIBUTE_NAME: 'cp-maxlength',
    MIN_ATTRIBUTE_NAME       : 'cp-min',
    ELSE_ATTRIBUTE_NAME      : 'cp-else',
    ELSE_IF_ATTRIBUTE_NAME   : 'cp-else-if',
    INIT_ATTRIBUTE_NAME      : 'cp-init',
    STYLE_ATTRIBUTE_NAME     : 'cp-style',
    CLASS_ATTRIBUTE_NAME     : 'cp-class',
    SRC_ATTRIBUTE_NAME       : 'cp-src',
    KEY_ATTRIBUTE_NAME       : 'cp-key',
    DISABLE_ATTRIBUTE_NAME   : 'cp-disabled',
    START_INTERPOLATION      : '[[',
    END_INTERPOLATION        : ']]',
    IGNORE_BINDINGS          : 'cp-non-bindable',
    FOCUS_ATTRIBUTE_NAME     : 'cp-focus',
    HIDE_ATTRIBUTE_NAME      : 'cp-hide',
    BLUR_ATTRIBUTE_NAME      : 'cp-blur',
};
