export const Constants = {
    SCOPE_ATTRIBUTE_NAME     : '$scope',
    REPEAT_ATTRIBUTE_NAME    : 'cp-repeat',
    REPEAT_INDEX_NAME        : '$index',
    REPEAT_ATTRIBUTE_OPERATOR: ' in ',
    MODEL_ATTRIBUTE_NAME     : 'cp-model',
    CLICK_ATTRIBUTE_NAME     : 'cp-click',
    SHOW_ATTRIBUTE_NAME      : 'cp-show',
    IF_ATTRIBUTE_NAME        : 'cp-if',
    ELSE_ATTRIBUTE_NAME      : 'cp-else',
    ELSE_IF_ATTRIBUTE_NAME   : 'cp-else-if',
    INIT_ATTRIBUTE_NAME      : 'cp-init',
    STYLE_ATTRIBUTE_NAME     : 'cp-style',
    CLASS_ATTRIBUTE_NAME     : 'cp-class',
    SRC_ATTRIBUTE_NAME       : 'cp-src',
    START_INTERPOLATION      : '[[',
    END_INTERPOLATION        : ']]',
};
