module.exports = Object.assign(
	require('./cpClass/test'),
	require('./cpClick/test'),
	require('./cpElse/test'),
	require('./cpElseIf/test'),
	require('./cpIf/test'),
	require('./cpInit/test'),
	require('./cpModel/test'),
	require('./cpRepeat/test'),
	require('./cpShow/test'),
	require('./cpSrc/test'),
	require('./cpStyle/test'),
	require('./interpolation/test'),
	require('./noBind/test'),
	require('./cpKey/test'),
);
